version: '3.8'

services:
    app:
        build: .
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - backend

    postgres:
        image: postgres:16-alpine
        restart: always
        env_file:
            - .env
        networks:
            - backend
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 3s
            retries: 5

volumes:
    postgres-db:

networks:
    backend:
        driver: bridge
